#!/bin/bash
echo "Copy MY PORTFOLIO WEB"
ssh master 'rm -rf ~/my-portfolio-web/build'
rsync -a -P /home/matthias/my-portfolio-web/build  Portfolio:~/my-portfolio-web
echo "MY PORTFOLIO WEB - copied"

